name: Test Results

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
permissions: {}

jobs:
  build:
    uses: awdware/dev/.github/workflows/test-results.yml@main
    secrets: inherit
